### ISSUE TITLE
Hardware Interfaces

### ISSUE THREAD

**Issue by rainwaffles** [rainwaffles/AVNewControl#4]
AVNavControl has interfaces to communicate with motors and sensors. As per Luke's specifications, we apparently have to make our interface not hardware-specific. I don't know how to do this.

**Comment by varun-magesh** [comment]
I'm working on vision ATM. Seth is more experienced about avr, but i'm pretty sure it's very hard to make this hardware independent. I think we could have a universal interface that connects with a simpler 'translator' that we can customise for whatever hardware we want to use.

**Comment by sethgirvan** [comment]
Are we still going to use this code? In github.com/avbotz/control luke is doing hardware abstraction with streams devices, the interfaces of which are provided by separate hardware-specific code

**Comment by rainwaffles** [comment]
yea this is deprecated :'(
